---
minio:
  address: localhost
  port: 9000
  accesskey: AKIAIOSFODNN7EXAMPLE
  secretkey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  ssl: false
gleaner:
  runid: t8  # this will be the bucket the output is placed in...
  summon: false # do we want to visit the web sites and pull down the files
  mill: false
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "http://schema.org/"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "https://schema.org"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "http://schema.org"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
summoner:
  mode: diff  # [time, hash, none] diff: look for difference or full: delete old objects and replace
millers:
  graph: true
  shacl: true
  prov: false
sources:
- name: ucar
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url:  https://data.ucar.edu/sitemap.xml 
  headless: false
- name: hydroshare
  logo: http://geodex.org/images/logos/cuahsiHydroshare.png
  url: https://www.hydroshare.org/sitemap-resources.xml
  headless: false
- name: unidata
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: https://thredds-test.unidata.ucar.edu/geocodesmap.xml
  headless: false
- name: iodpss
  logo: https://ssdb.iodp.org/images/head_logo_PRO.gif
  url: https://ssdb.iodp.org/dataset/sitemap.xml
  headless: false
