version: '3'

services:  
  minio:
    image: minio/minio:latest
    ports:
     - 9000:9000
    environment:
     - SERVICE_PORTS=9000
     - MINIO_ACCESS_KEY=gleaneraccess
     - MINIO_SECRET_KEY=gleanersecret
    volumes:
     - "$DATAVOL/s3/data:/data"
     - "$DATAVOL/s3/config:/root/.minio"
    networks:
      - web
    command: ["server", "/data"]

  tangram:
    image: fils/p418tangram:0.1.15
    ports:
       - "8080:8080"
    networks:
       - web

  headless:
    image: chromedp/headless-shell:latest
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222
    environment:
     - SERVICE_PORTS=9222
    networks:
      - web

  jena:
    image: fcore/p418jena:0.1.11
    ports:
       - "3030:3030"
    volumes:
       - $DATAVOL/jena/data:/data
    networks:
       - web

networks:
  web:
    driver: overlay

