version: '3'

# The deployment I use for development work in Gleaner

services:
  mc:
    image: minio/mc:latest

  gleaner:
    image: nsfearthcube/gleaner:latest

  tika:
    image: logicalspark/docker-tikaserver
    ports:
      - 9998:9998
    environment:
      - SERVICE_PORTS=9998
    networks:
      - web

  minio:
    image: minio/minio:latest
    ports:
     - 9000:9000
    env_file:
     - ./prod.env
    environment:
     - SERVICE_PORTS=9000
     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
     - "$DATAVOL/s3/data:/data"
     - "$DATAVOL/s3/config:/root/.minio"
    networks:
      - web
    command: ["server", "/data"]

  tangram:
    image: fils/p418tangram:0.1.15
    ports:
      - "8080:8080"
    networks:
      - web

  headless:
    image: chromedp/headless-shell:latest
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222
    environment:
     - SERVICE_PORTS=9222
    networks:
      - web

  jena:
    image: fcore/p418jena:0.1.11
    env_file:
     - ./prod.env
    ports:
       - "3030:3030"
    volumes:
       - $DATAVOL/jena/data:/data
    networks:
       - web

  tile38:
    image: tile38/tile38
    ports:
     - 9851:9851
    env_file:
     - ./prod.env
    environment:
     - SERVICE_PORTS=9851
    volumes:
      - "${DATAVOL}/spatialindex:/data"
    networks:
      - web

networks:
  web:
    driver: overlay

