apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
    traefik.backend: headlesschrome
    traefik.port: "9222"
  creationTimestamp: null
  labels:
    io.kompose.service: headless
  name: headless
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: headless
    spec:
      containers:
      - env:
        - name: SERVICE_PORTS
          value: "9222"
        image: chromedp/headless-shell:latest
        name: headless
        ports:
        - containerPort: 9222
        resources: {}
      restartPolicy: Always
status: {}
