apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jena
  name: jena
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jena
    spec:
      containers:
      - env:
        - name: DATAVOL
          valueFrom:
            configMapKeyRef:
              key: DATAVOL
              name: jena-prod-env
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_ACCESS_KEY
              name: jena-prod-env
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_SECRET_KEY
              name: jena-prod-env
        image: fcore/p418jena:0.1.11
        name: jena
        ports:
        - containerPort: 3030
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: jena-claim0
      restartPolicy: Always
      volumes:
      - name: jena-claim0
        persistentVolumeClaim:
          claimName: jena-claim0
status: {}
