apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jena
  name: jena
spec:
  ports:
  - name: "3030"
    port: 3030
    targetPort: 3030
  selector:
    io.kompose.service: jena
status:
  loadBalancer: {}
