apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
    traefik.backend: shacl
    traefik.port: "7000"
  creationTimestamp: null
  labels:
    io.kompose.service: shacl
  name: shacl
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    io.kompose.service: shacl
status:
  loadBalancer: {}
