apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
    traefik.backend: shacl
    traefik.port: "7000"
  creationTimestamp: null
  labels:
    io.kompose.service: shacl
  name: shacl
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shacl
    spec:
      containers:
      - image: fcore/shaclservice:0.1.4
        name: shacl
        ports:
        - containerPort: 7000
        resources: {}
      restartPolicy: Always
status: {}
