apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tika
  name: tika
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tika
    spec:
      containers:
      - env:
        - name: SERVICE_PORTS
          value: "9998"
        image: logicalspark/docker-tikaserver
        name: tika
        ports:
        - containerPort: 9998
        resources: {}
      restartPolicy: Always
status: {}
