apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tile38
  name: tile38
spec:
  ports:
  - name: "9851"
    port: 9851
    targetPort: 9851
  selector:
    io.kompose.service: tile38
status:
  loadBalancer: {}
