apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tile38
  name: tile38
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tile38
    spec:
      containers:
      - env:
        - name: DATAVOL
          valueFrom:
            configMapKeyRef:
              key: DATAVOL
              name: tile38-prod-env
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_ACCESS_KEY
              name: tile38-prod-env
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_SECRET_KEY
              name: tile38-prod-env
        - name: SERVICE_PORTS
          value: "9851"
        image: tile38/tile38
        name: tile38
        ports:
        - containerPort: 9851
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: tile38-claim0
      restartPolicy: Always
      volumes:
      - name: tile38-claim0
        persistentVolumeClaim:
          claimName: tile38-claim0
status: {}
