version: '3'

services:
  tika:
   image: logicalspark/docker-tikaserver
   ports:
     - 9998
   environment:
     - SERVICE_PORTS=9998
   deploy:
     replicas: 6
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - webha

 
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - tika
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - webha
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webha:
    driver: overlay


