apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f gleaner-dev.yaml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: DATAVOL
          valueFrom:
            configMapKeyRef:
              key: DATAVOL
              name: minio-prod-env
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_ACCESS_KEY
              name: minio-prod-env
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_SECRET_KEY
              name: minio-prod-env
        - name: SERVICE_PORTS
          value: "9000"
        image: minio/minio:latest
        name: minio
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-claim0
        - mountPath: /root/.minio
          name: minio-claim1
      restartPolicy: Always
      volumes:
      - name: minio-claim0
        persistentVolumeClaim:
          claimName: minio-claim0
      - name: minio-claim1
        persistentVolumeClaim:
          claimName: minio-claim1
status: {}
