---
gleaner:
  summon: false  # do we want to visit the web sites and pull down the files
  mill: true
  runid: nertestone  # this will be the bucket the output is placed in...
millers:
  mock: false
  graph: true
  spatial: false
  shacl: true
  organic: false
  tika: false
  fdptika: false
  fdptikajena: false
  fdpgraph: false
  prov: false
  ner: true
sources:
- name: thredds-testunidataucaredu
  shortname: unidata
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: https://thredds-test.unidata.ucar.edu/geocodesmap.xml
  headless: false
  sitemapformat: xml
  active: true
- name: opencoredataorg
  shortname: opencore
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: https://opencoredata.org/sitemap.xml
  headless: false
  sitemapformat: xml
  active: true
- name: ssdbiodporg
  shortname: ssdb
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: https://foo.org/sitemap.xml
  headless: false
  sitemapformat: xml
  active: true
