---
minio:
  address: localhost
  port: 9000
  accesskey: MySecretAccessKey
  secretkey: MySecretSecretKeyforMinio
  ssl: false
gleaner:
  runid: ocdbco1  # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
  tmpdir: ""
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "http://schema.org/"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "https://schema.org"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "http://schema.org"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
summoner:
  mode: diff  # [time, hash, none] diff: look for difference or full: delete old objects and replace
millers:
  graph: true
  shacl: false
  prov: false
sources:
- name: ocd
  logo: http://geodex.org/images/logos/ocd_logo.jpg
  url: http://opencoredata.org/sitemap.xml
  headless: false
- name: bcodmo
  logo: http://geodex.org/images/logos/bco-dmo-words-BLUE.jpg
  url: https://www.bco-dmo.org/sitemap.xml
  headless: false
