---
gleaner:
  summon: false  # do we want to visit the web sites and pull down the files
  mill: true
  runid: runtwo  # this will be the bucket the output is placed in...
millers:
  mock: false
  graph: false
  spatial: false
  shacl: true
  organic: false
  tika: false
  fdptika: false
  fdptikajena: false
  fdpgraph: false
  prov: false
sources:
- name: thredds-testunidataucaredu
  shortname: unidata
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: https://thredds-test.unidata.ucar.edu/geocodesmap.xml
  headless: false
  sitemapformat: xml
  active: true
